{
    "type": "record",
    "name": "account",
    "fields": [
        {
            "name": "account_id",
            "type": "int"
        },
        {
            "name": "district_id",
            "type": "string"
        },
        {
            "name": "frequency",
            "type": "string"
        },
        {
            "name": "parseddate",
            "type": {
                "type": "int",
                "logicalType": "date"
            }
        },
        {
            "name": "year",
            "type": "int"
        },
        {
            "name": "month",
            "type": "int"
        },
        {
            "name": "day",
            "type": "int"
        }
    ]
}
