{
    "type": "record",
    "name": "card",
    "fields": [
        {
            "name": "card_id",
            "type": "string"
        },
        {
            "name": "disp_id",
            "type": "string"
        },
        {
            "name": "type",
            "type": "string"
        },
        {
            "name": "year",
            "type": "int"
        },
        {
            "name": "month",
            "type": "int"
        },
        {
            "name": "day",
            "type": "int"
        },
        {
            "name": "fulldate",
            "type": {
                "type": "int",
                "logicalType": "date"
            }
        }
    ]
}
