database:
  snowflake:
    user: your_import_user
    password: your_password
    account: your_snowflake_account
    warehouse: IMPORT_WH
    database: STAGING
    schema: RAW
    avro_schema_path: path_to_avro_schema

kafka:
  bootstrap_servers: your_kafka_bootstrap_servers
  topic: your_kafka_topic
  group_id: import_group
  auto_offset_reset: latest
  enable_auto_commit: true

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]
