--------------------------------------------------------------------------
--- 4. ADD RESOURCE MONITORS WITH 100 CREDITS A MONTH FOR ALERTING
--------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
 CREATE RESOURCE MONITOR identifier($V_MONITOR_BI) WITH 
 CREDIT_QUOTA = 100 , frequency = 'MONTHLY', start_timestamp = 'IMMEDIATELY'
 TRIGGERS 
 ON 50 PERCENT DO NOTIFY 
 ON 75 PERCENT DO NOTIFY
 ON 95 PERCENT DO SUSPEND
 ON 100 PERCENT DO SUSPEND_IMMEDIATE ;
 
ALTER WAREHOUSE identifier($V_WHNAME_BI) SET RESOURCE_MONITOR = $V_MONITOR_BI;



   
 CREATE RESOURCE MONITOR identifier($V_MONITOR_IMPORT) WITH 
 CREDIT_QUOTA = 100, frequency = 'MONTHLY', start_timestamp = 'IMMEDIATELY'
 TRIGGERS 
 ON 50 PERCENT DO NOTIFY 
 ON 75 PERCENT DO NOTIFY
 ON 95 PERCENT DO SUSPEND
 ON 100 PERCENT DO SUSPEND_IMMEDIATE ;
 
ALTER WAREHOUSE identifier($V_WHNAME_IMPORT) SET RESOURCE_MONITOR = $V_MONITOR_IMPORT;



 CREATE RESOURCE MONITOR identifier($V_MONITOR_TRANSFORM) WITH 
 CREDIT_QUOTA = 100, frequency = 'MONTHLY', start_timestamp = 'IMMEDIATELY'
 TRIGGERS  
 ON 50 PERCENT DO NOTIFY 
 ON 75 PERCENT DO NOTIFY
 ON 95 PERCENT DO SUSPEND
 ON 100 PERCENT DO SUSPEND_IMMEDIATE ;
 
ALTER WAREHOUSE identifier($V_WHNAME_TRANSFORM) SET RESOURCE_MONITOR = $V_MONITOR_TRANSFORM;